version: "1.0"
info:
  model: int-scaffold
packages:
- name: ProjectEmptyRepoProject
  gitServerName: rajka
  gitUrl: https://github.com/rajkapoor-rajkapoor
  gitUsername: rajkapoor-rajkapoor
  gitBranch: main
services:
- serviceName: project.projectemptyrepo.integrations:DAFTest
  packages:
  - name: ProjectEmptyRepoProject
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2077
